### ISSUE TITLE
Secure way of getting the URLs out of KeePass

### ISSUE THREAD

**Issue by dannoe** [jinks/passbleed#2]
- Select the root group of your KeePass database.
- Select all entries. (Shortcut: CTRL+A)
- Right-click and select URL -> Copy to clipboard (Shortcut: CTRL+SHIFT+U)
- Paste your clipboard content into a file.

Edit: Maybe you could add an command-line switch for this method? So you don't have to use a .csv file as input.

**Comment by jinks** [comment]
I think this goes beyond the scope I am willing to work on personally.

I wrote this as a "quick fix" for my own problem and I already had a secure place to put the CSV. Your solution also only works with the original C# KeePass, so it's another special case.

**Comment by jinks** [comment]
OK, latest update __kind of__ allows this now. LastPass has the URL in the first column, so if you construct a list of URLs with the first line being "url" (with or without quotes, case sensitive) the program will treat it as a 1-column CSV.

**Comment by dannoe** [comment]
I am sorry, but I already used PowerShell/grep for diffing my URLs. Thanks anyway!
